# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token c06340b4b90b4f92cd03d6a9501c6f96a68c55c1

{
  "title": "Стул",
  "description": "Продам срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 6f802ee27c7738b5bc36cdeb5b4b59c0e0228c1a

{
  "status": "CLOSED"
}

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2021-11-24
Content-Type: application/json
